import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Loginbtn from '../components/Loginbtn'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cover Letter Generator</h1>

        <p className={styles.description}>
          Get started by logging into your Github account.
        </p>

        <Loginbtn />
        <div className={styles.grid}>
          <Link href="/about">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>About</h2>
              <p>Learn about the stack used to make this</p>
            </a>
          </Link>

          <Link href="/example">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Example Letter</h2>
              <p>See this tool with generic inputs</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
