import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Letter Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google-site-verification" content="z-FQu6t6zVW07IPorVEr2ZRzRgdwxAQZTHYVzanyuk8" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📰</text></svg>"
        />
      </Head>

      <h1 className={styles.title}>Letter Starter</h1>

      <p className={styles.description}>
        Get started by logging into your Github account.
      </p>
      <div className={styles.grid}>
        <Link href="/about" className={styles.card}>

          <h2>About</h2>
          <p>Learn about the stack used to make this</p>

        </Link>

        <Link href="/example" className={styles.card}>

          <h2>Example Letter</h2>
          <p>See this tool with generic inputs</p>

        </Link>
        <Link href="/disclaimer" className={styles.card}>

          <h2>Disclaimer</h2>
          <p>Make sure you know what you are using!</p>

        </Link>
        <Link href="/demo" className={styles.card}>

          <h2>Demo</h2>
          <p>Try it out</p>

        </Link>
      </div>
    </div>
  );
}
